pipeline {
    agent any

    environment {

        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = credentials('aws-account-id')

        ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_REGISTRY_URL = "https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        AWS_CREDENTIALS = 'aws-ecr-credentials'
        ECR = 'ecr'

        DB_IMAGE_DEV = 'employee-management-frontend-dev'
        DB_IMAGE_QA = 'employee-management-frontend-qa'
        DB_IMAGE_UAT = 'employee-management-frontend-uat'
        DB_IMAGE_PROD = 'employee-management-frontend-prod'

        BUILD_CONTEXT = './frontend'

        ECS_CLUSTER = 'employee-management-dev'

        ECS_SERVICE_DEV = 'employee-management-frontend-dev'
        ECS_SERVICE_QA = 'employee-management-frontend-qa'
        ECS_SERVICE_UAT = 'employee-management-frontend-uat'
        ECS_SERVICE_PROD = 'employee-management-frontend-prod'

        ECS_TASK_FAMILY = 'employee_management_Frontend'
    }

    parameters {

        choice(
            name: 'Environment',
            choices: ['dev', 'qa', 'uat', 'prod'],
            description: 'Select the Environment'
        )
    }

    stages {

        stage('Dev - Build & Push') {

            when {
                expression {
                    params.Environment == 'dev'
                }
            }

            steps {

                script {

                    buildAndPush(
                        env.DB_IMAGE_DEV,
                        env.BUILD_CONTEXT
                    )
                }
            }
        }


        // stage('Dev - Deploy to ECS') {

        //     when {
        //         expression {
        //             params.Environment == 'dev'
        //         }
        //     }

        //     steps {

        //         script {

        //             deployToECS(
        //                 'backend/task-definition.json',
        //                 env.ECS_TASK_FAMILY,
        //                 env.ECS_SERVICE_DEV
        //             )
        //         }
        //     }
        // }

        stage('Promote Dev to QA') {

            when {
                expression {
                    params.Environment == 'qa'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.DB_IMAGE_DEV,
                        env.DB_IMAGE_QA
                    )
                }
            }
        }


        // stage('QA - Deploy to ECS') {

        //     when {
        //         expression {
        //             params.Environment == 'qa'
        //         }
        //     }

        //     steps {

        //         script {

        //             deployToECS(
        //                 'backend/task-definition.json',
        //                 env.ECS_TASK_FAMILY,
        //                 env.ECS_SERVICE_QA
        //             )
        //         }
        //     }
        // }

        stage('Promote QA to UAT') {

            when {
                expression {
                    params.Environment == 'uat'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.DB_IMAGE_QA,
                        env.DB_IMAGE_UAT
                    )
                }
            }
        }


        // stage('UAT - Deploy to ECS') {

        //     when {
        //         expression {
        //             params.Environment == 'uat'
        //         }
        //     }

        //     steps {

        //         script {

        //             deployToECS(
        //                 'backend/task-definition.json',
        //                 env.ECS_TASK_FAMILY,
        //                 env.ECS_SERVICE_UAT
        //             )
        //         }
        //     }
        // }

        stage('Approval for Prod Deployment') {

            when {
                expression {
                    params.Environment == 'prod'
                }
            }

            steps {

                input(
                    message: 'Promote UAT image to PROD?',
                    ok: 'Proceed'
                )
            }
        }

        stage('Promote UAT to PROD') {

            when {
                expression {
                    params.Environment == 'prod'
                }
            }

            steps {

                script {

                    promoteImage(
                        env.DB_IMAGE_UAT,
                        env.DB_IMAGE_PROD
                    )
                }
            }
        }


        // stage('PROD - Deploy to ECS') {

        //     when {
        //         expression {
        //             params.Environment == 'prod'
        //         }
        //     }

        //     steps {

        //         script {

        //             deployToECS(
        //                 'backend/task-definition.json',
        //                 env.ECS_TASK_FAMILY,
        //                 env.ECS_SERVICE_PROD
        //             )
        //         }
        //     }
        // }
    }

    post {

        always {

            deleteDir()
        }
    }
}

def buildAndPush(String imageRepository, String buildContext) {

    echo "Repository : ${imageRepository}"
    echo "Commit     : ${env.GIT_COMMIT}"


    def image = docker.build(
        "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}",
        buildContext
    )


    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        image.push()
    }


    echo "Image pushed successfully"

    echo "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}"
}

def promoteImage(String sourceImage, String targetImage) {

    echo "Source : ${sourceImage}:${env.GIT_COMMIT}"
    echo "Target : ${targetImage}:${env.GIT_COMMIT}"

    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        docker.image(
            "${env.ECR_REGISTRY}/${sourceImage}:${env.GIT_COMMIT}"
        ).pull()
    }

    sh """
        docker tag \
        ${env.ECR_REGISTRY}/${sourceImage}:${env.GIT_COMMIT} \
        ${env.ECR_REGISTRY}/${targetImage}:${env.GIT_COMMIT}
    """

    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        docker.image(
            "${env.ECR_REGISTRY}/${targetImage}:${env.GIT_COMMIT}"
        ).push()
    }


    echo "Image promoted successfully"

    echo "${env.ECR_REGISTRY}/${targetImage}:${env.GIT_COMMIT}"
}

def deployToECS(String taskDefinitionFile, String taskFamily, String ecsService) {

    sh """
        sed -i 's/\\\${ENV}/${params.Environment}/g' ${taskDefinitionFile}
        sed -i 's/\\\${COMMIT_ID}/${env.GIT_COMMIT}/g' ${taskDefinitionFile}
    """

    def taskRevision = sh(
        script: """
            aws ecs register-task-definition \
                --cli-input-json file://${taskDefinitionFile} \
                --region ${env.AWS_REGION} \
                --query 'taskDefinition.revision' \
                --output text
        """,
        returnStdout: true
    ).trim()

    sh """
        aws ecs update-service \
            --cluster ${env.ECS_CLUSTER} \
            --service ${ecsService} \
            --task-definition ${taskFamily}:${taskRevision} \
            --region ${env.AWS_REGION}
    """
}