pipeline {
    agent any

    environment {
        AWS_REGION           = 'ap-south-1'
        AWS_ACCOUNT_ID       = credentials('aws-account-id')
        ECR_REGISTRY         = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_REGISTRY_URL     = "https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        AWS_CREDENTIALS      = 'aws-ecr-credentials'
        ECR                  = 'ecr'
        BACKEND_IMAGE        = 'app-backend'
        BUILD_CONTEXT        = './backend'
        ECS_CLUSTER          = 'app-ecs-cluster'
        ECS_SERVICE          = 'app-backend-service'
        ECS_TASK_FAMILY      = 'app-backend'
        TASK_DEFINITION      = 'backend/task-definition.json'
    }

    parameters {
        choice(
            name: 'Environment',
            choices: ['dev', 'qa', 'uat', 'prod'],
            description: 'Select the Environment'
        )
        string(
            name: 'IMAGE_TAG',
            defaultValue: '',
            description: 'provide commit id'
        )
    }

    stages {
        stage('Dev - Build & Push') {
            when {
                expression {
                    params.Environment == 'dev'
                }
            }
            steps {
                script {
                    buildAndPush(
                        "${env.BACKEND_IMAGE}-${params.Environment}",
                        env.BUILD_CONTEXT
                    )
                }
            }
        }

        stage('Dev - Deploy to ECS') {
            when {
                expression {
                    params.Environment == 'dev'
                }
            }
            steps {
                script {
                    deployToECS(
                        env.TASK_DEFINITION
                    )
                }
            }
        }

        stage('Promote Dev to QA') {
            when {
                expression {
                    params.Environment == 'qa'
                }
            }
            steps {
                script {
                    promoteImage(
                        "${env.BACKEND_IMAGE}-dev",
                        "${env.BACKEND_IMAGE}-${params.Environment}"
                    )
                }
            }
        }

        stage('QA - Deploy to ECS') {
            when {
                expression {
                    params.Environment == 'qa'
                }
            }
            steps {
                script {
                    deployToECS(
                        env.TASK_DEFINITION
                    )
                }
            }
        }

        stage('Promote QA to UAT') {
            when {
                expression {
                    params.Environment == 'uat'
                }
            }
            steps {
                script {
                    promoteImage(
                        "${env.BACKEND_IMAGE}-qa",
                        "${env.BACKEND_IMAGE}-${params.Environment}"
                    )
                }
            }
        }

        stage('UAT - Deploy to ECS') {
            when {
                expression {
                    params.Environment == 'uat'
                }
            }
            steps {
                script {
                    deployToECS(
                        env.TASK_DEFINITION
                    )
                }
            }
        }

        stage('Approval for Prod Deployment') {
            when {
                expression {
                    params.Environment == 'prod'
                }
            }
            steps {
                input(
                    message: 'Promote UAT image to PROD?',
                    ok: 'Proceed'
                )
            }
        }

        stage('Promote UAT to PROD') {
            when {
                expression {
                    params.Environment == 'prod'
                }
            }
            steps {
                script {
                    promoteImage(
                        "${env.BACKEND_IMAGE}-uat",
                        "${env.BACKEND_IMAGE}-${params.Environment}"
                    )
                }
            }
        }

        stage('PROD - Deploy to ECS') {
            when {
                expression {
                    params.Environment == 'prod'
                }
            }
            steps {
                script {
                    deployToECS(
                        env.TASK_DEFINITION
                    )
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}

def buildAndPush(String imageRepository, String buildContext) {
    echo "Repository : ${imageRepository}"
    echo "Commit     : ${env.GIT_COMMIT}"
    def image = docker.build(
        "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}",
        buildContext
    )
    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {

        image.push()
    }
    echo "Image pushed successfully"
    echo "${env.ECR_REGISTRY}/${imageRepository}:${env.GIT_COMMIT}"
}

def promoteImage(String sourceImage, String targetImage) {
    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {
        docker.image(
            "${env.ECR_REGISTRY}/${sourceImage}:${params.IMAGE_TAG}"
        ).pull()
    }
    sh """
        docker tag \
        ${env.ECR_REGISTRY}/${sourceImage}:${params.IMAGE_TAG} \
        ${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}
    """
    docker.withRegistry(
        "${env.ECR_REGISTRY_URL}",
        "${env.ECR}:${env.AWS_REGION}:${env.AWS_CREDENTIALS}"
    ) {
        docker.image(
            "${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}"
        ).push()
    }
    echo "Image promoted successfully"
    echo "${env.ECR_REGISTRY}/${targetImage}:${params.IMAGE_TAG}"
}

def deployToECS(String taskDefinitionFile) {

    def environment = params.Environment
    def taskFamily  = "${env.ECS_TASK_FAMILY}-${environment}"
    def ecsService  = "${env.ECS_SERVICE}-${environment}"
    def ecsCluster  = "${env.ECS_CLUSTER}-${environment}"

    if(params.Environment == 'dev'){
        sh """
            sed -i 's/\\\${ENV}/${params.Environment}/g' ${taskDefinitionFile}
            sed -i 's/\\\${COMMIT_ID}/${env.GIT_COMMIT}/g' ${taskDefinitionFile}
        """
    }else{
        sh """
            sed -i 's/\\\${ENV}/${params.Environment}/g' ${taskDefinitionFile}
            sed -i 's/\\\${COMMIT_ID}/${params.IMAGE_TAG}/g' ${taskDefinitionFile}
        """
    }
    withCredentials([
        [$class: 'AmazonWebServicesCredentialsBinding',
         credentialsId: env.AWS_CREDENTIALS]
    ]){
        def taskRevision = sh(
            script: """
                aws ecs register-task-definition \
                    --cli-input-json file://${taskDefinitionFile} \
                    --region ${env.AWS_REGION} \
                    --query 'taskDefinition.revision' \
                    --output text
            """,
            returnStdout: true
        ).trim()
        sh """
            aws ecs update-service \
                --cluster ${ecsCluster} \
                --service ${ecsService} \
                --task-definition ${taskFamily}:${taskRevision} \
                --region ${env.AWS_REGION}
        """
    }
}